name: Build Release Kernel

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        model: [ "T860", "T865" ]

    steps:
    - uses: actions/checkout@v1
    - name: Install mkbootimg
      run: |
        wget -q https://android.googlesource.com/platform/system/tools/mkbootimg/+archive/refs/heads/master.tar.gz -O - | tar xzf - mkbootimg.py
        chmod +x mkbootimg.py
        sudo mv mkbootimg.py /usr/local/bin/mkbootimg
    - name: Install avbtool
      run: |
        wget -q https://android.googlesource.com/platform/external/avb/+archive/refs/heads/android10-dev.tar.gz -O - | tar xzf - avbtool
        chmod +x avbtool
        sudo mv avbtool /usr/local/bin/avbtool
    - name: Clone Submodules
      run: git submodule update --init --recursive
    - name: Kernel Configure
      run: |
        ./build config                       \
                os_patch_level=2020-05       \
                model=${{ matrix.model}}     \
                name=420rom-BTF2-v10.7.1-Rel \
                +magisk                      \
                +nohardening                 \
                +nodebug                     \
                +noatime                     \
                +ttl                         \
                +wireguard                   \
                +mass_storage                \
                +cifs                        \
                +sdfat                       \
                +ntfs                        \
                +morosound                   \
                +io_maple                    \
                +io_fiops                    \
                +io_sio                      \
                +io_zen                      \
                +io_anxiety                  \
                +io_noop                     \
                +io_cfq                      \
                +sched_ondemand              \
                +sched_powersave             \
                +sched_userspace             \
                +sched_performance           \
                +sched_conservative          \
                +tcp_westwood                \
                +tcp_htcp                    \
                +tcp_cubic                   \
                +tcp_bbr                     \
                +tcp_bic                     \
                +boeffla_wl_blocker          \
        2>&1 | tee config.info
    - name: Kernel Build
      run: ./build :build
    - name: Create boot.img
      run: ./build :mkimg
    - name: Upload Kernel
      uses: actions/upload-artifact@v2
      with:
        name: 420rom-BTF2-v10.7.1-${{ matrix.model }}-Release-Kernel
        path: boot.img
    - name: Upload Kernel Info
      uses: actions/upload-artifact@v2
      with:
        name: ConfigurationInfo-v10.7.1-${{ matrix.model }}-Release-Kernel
        path: config.*
